### ISSUE TITLE
Add extensive help text

### ISSUE THREAD

**Issue by BexPerchard** [g4he/g4he#121]
Can we improve the help text to be more clear on the following: 
How are the values ascertained?  
How are collaborations classified?  
Are the values per institution or total?  
What is the quality and completeness of the source data?  
Are there variations across the Councils?

**Comment by richard-jones** [comment]
I've added a bunch of help text, but need to confirm that I've covered all the bases, when the above descriptive text is expanded

**Comment by richard-jones** [comment]
In terms of help text, this issue is complete.  There are a couple of other questions.

What is the quality and completeness of the source data?
- it's difficult to answer this in text.  I think that issue #124 is probably where this gets dealt with

Are there variations across the Councils?
- again, #124 probably answers this
